name: Run Audit and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.x in order to write go.list file
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: WriteGoList
        run: go list -json -m all > go.list

      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: 	make test coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true